### ISSUE TITLE
allow any AbstractVector in roc

### ISSUE THREAD

**Issue by bkamins** [davidavdav/ROCAnalysis.jl#25]
Currently you have:
```
roc(tar::Vector{T}, non::Vector{T}; laplace, collapse) where T<:Real
```
which is quite restrictive.

Would you consider loosening the signature to:
```
roc(tar::AbstractVector, non::AbsrtractVector; laplace, collapse)
```
and internally check if `tar` and `non` contain only `Real` values?

This would allow:
* any abstract vector, mainly views
* having `tar` and `non` element type to be e.g. `Union{Missing, Float64}` which is often hit in practice when processing data (i.e. column allows missings, but actually it does not have it as user has manually dropped them, but without changing `eltype` of column)

Thank you!

**Comment by davidavdav** [comment]
Hello, 

Going from `Vector` to `AbstractVector` is definitely the way forward.  As for the type of the element, sure we can relax that, but this makes the code somewhat slower, right?  Maybe we can have an additional relaxed signature that does the checking and then calls the strict signature?

**Comment by bkamins** [comment]
> Maybe we can have an additional relaxed signature that does the checking and then calls the strict signature?

Yes

**Comment by davidavdav** [comment]
I pushed a new version.  It appears that Travis is no longer working, so I don't know how to deal with CI right now.  

Maybe you can test it.

**Comment by bkamins** [comment]
you need to switch to GitHub Actions. I do not know exactly how to do it, it should be relatively simple.

The commit looks good. Thank you!

**Comment by bkamins** [comment]
Thank you!
