### ISSUE TITLE
AUC computation seems wrong

### ISSUE THREAD

**Issue by chrisn-pik** [davidavdav/ROCAnalysis.jl#26]
```julia
using ROCAnalysis, MultivariateAnomalies
ŷ = [0, 1, 1, 1, 1, 0, 1 ,0 ,1]
y = [0, 1, 1, 1, 1, 0, 0 ,0 ,1]

rocAnalysis_roc = ROCAnalysis.roc(y,ŷ)
rocAnalysis_auc = auc(rocAnalysis_roc)

mA_auc = MultivariateAnomalies.auc(ŷ,y)
```
where y is the ground truth and ŷ the prediction.
I get: ```rocAnalysis_auc``` = 0.5555555555555556 and ```mA_auc``` = 0.875

using python, I have the following:
```python
from sklearn.metrics import roc_auc_score
ŷ = [0, 1, 1, 1, 1, 0, 1 ,0 ,1]
y = [0, 1, 1, 1, 1, 0, 0 ,0 ,1]
roc_auc_score(y, ŷ)
0.875
```

**Comment by davidavdav** [comment]
Hello, 

Thanks for asking, I had to dive into this, not using AUC values myself a lot.  The interface is different, the `roc` function works with `target` and `nontarget` scores.  You are feeding the function "classes" and "predictions", which are different things. 

Admittedly, `auc()` and `AUC` are not very well documented in this package. 
```julia
julia> targets = ŷ[y .== 1]
5-element Vector{Int64}:
 1
 1
 1
 1
 1

julia> nontargets = ŷ[y .== 0]
4-element Vector{Int64}:
 0
 0
 1
 0

julia> auc(roc(targets, nontargets))
0.125

julia> AUC(roc(targets, nontargets))
0.875
```
`AUC()` is probably what you want.   This package prefers metrics that are "error-like", things we want to minimize.

**Comment by chrisn-pik** [comment]
@davidavdav Thanks for the quick and helpful reply! I think that the issue can be closed, unless it should remain open to change the documentation.
