### ISSUE TITLE
Compat StatsBase.jl

### ISSUE THREAD

**Issue by bkamins** [davidavdav/ROCAnalysis.jl#27]
@davidavdav - can we allow StatsBase.jl 0.34 in this package? I think it should be OK.

**Comment by davidavdav** [comment]
Sure, I think I don't even need StatsBase, as I can't find it anywhere in the code.  Could it be that some functions moved to/from SpecialFunctions?

**Comment by bkamins** [comment]
A release would be appreciated :). Thank you!
