### ISSUE TITLE
Update to support DataFrames v0.11

### ISSUE THREAD

**Issue by ValdarT** [davidavdav/ROCAnalysis.jl#5]
Installing this package downgrades DataFrames and related packages.

**Comment by diegozea** [comment]
I updated DataFrames by using `Pkg.checkout`. But now I get the following error when I do `using ROCAnalysis`:

```
LoadError: LoadError: UndefVarError: DataArray not defined
while loading /home/dzea/.julia/v0.6/ROCAnalysis/src/modules.jl, in expression starting on line 8
while loading /home/dzea/.julia/v0.6/ROCAnalysis/src/ROCAnalysis.jl, in expression starting on line 10
```

**Comment by davidavdav** [comment]
I don't really understand why installing this would downgrade another package.  Is that because there is a version number in REQUIRE?  That was put there on request by the Metadata maintainer, I believe. 

I'll up the requirements to 0.6 and see what we can do there for DataFrames.

**Comment by ValdarT** [comment]
Yep, DataFrames v0.11+ is Julia v0.6+ only. 

Note that DataArray is not part of DataFrames anymore so it can't be imported from there. The default way for missing values is `Array{Union{T, Missing}}` and DataArray lives in a [separate package](https://github.com/JuliaStats/DataArrays.jl) now.

**Comment by davidavdav** [comment]
I don't really get the package system.  In a local copy I seem to be stuck at DataFrames 0.10.1, and however often I try to `Pkg.update()` or `Pkg.update("DataFrames")`, nothing gets updated.

**Comment by ValdarT** [comment]
`Pkg.update()` updates to the maximum versions that won't conflict. So you have some package installed that conflicts with the new DataFrames, for example Gadfly. See this [Discourse thread](https://discourse.julialang.org/t/how-to-upgrade-from-dataframes-0-10-1-to-0-11-3/8243/) and [this DataFrames issue](https://github.com/JuliaData/DataFrames.jl/issues/1232).

**Comment by davidavdav** [comment]
Well, I ended up just removing `~/.julia/v0.6` altogether.  The nuclear option.  Then I had the opportunity to look at all the new DataFrames-isms.  I had to put `CSV` and `GZip` in REQUIRE, just for testing.   I wonder if there is a format for specifying packages only required for testing and not for the package itself. 

This should now be fixed in 21aef7e, I've sent a PR to METADATA.jl.

**Comment by ValdarT** [comment]
> I wonder if there is a format for specifying packages only required for testing and not for the package itself.

Yes. [As per official documentation:](https://docs.julialang.org/en/stable/manual/packages/#Creating-a-new-Package-1) "Lastly, in many cases you may need extra packages for testing. Additional packages which are only required for tests should be specified in the `test/REQUIRE` file. This `REQUIRE` file has the same specification as the standard `REQUIRE` file."

**Comment by davidavdav** [comment]
Thanks, got that.

**Comment by davidavdav** [comment]
Issue should be resolved in https://github.com/JuliaLang/METADATA.jl/pull/13066#event-1445001913
